---
title: "Consulting HW6"
author: "Billie"
date: "2024-10-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}

clean_dat <- read.csv("../DataProcessed/lead-iq-01.clean.csv")


boxplot(IQ ~ Smelter,
        data=clean_dat,
        main = "Boxplot of IQ Scores by Smelter Group", 
        xlab = "Smelter", 
        ylab = "IQ", 
        col = "lightblue", 
        border = "darkblue")

far_mean <- mean(clean_dat$IQ[clean_dat$Smelter == "Far"])
near_mean <- mean(clean_dat$IQ[clean_dat$Smelter == "Near"])

summary_stats <- data.frame(
  Statistic = c("Mean (far)", "Mean (near)"),
  Value = c(far_mean, near_mean)
)

# Display the table using knitr's kable
knitr::kable(summary_stats, col.names = c("Statistic", "Value"))
```

The mean IQ is lower for the near group. By observing the boxplot, it can be seen that the mass of the data is generally lower for the near group. This suggests that living near the smelter negatively impacts IQ, but further analysis will be needed.